import os
import json
import numpy
import arrow
import base64
import pandas
import pathlib
import fuzzyset
import pendulum
import itertools
import traceback
import subprocess
import collections
from tqdm import tqdm
from Bio import SeqIO
from time import sleep
from Bio.Seq import Seq
from dotenv import load_dotenv
from pandas import ExcelWriter
from websocket import create_connection
from zipfile import ZipFile, ZIP_DEFLATED

def send_data_to_websocket(data_type, tool, message):
	load_dotenv('.env')
	ws = create_connection(f"ws://{os.getenv('WEBSOCKET_URL')}/{os.getenv('BASE_URL')}wsa/backend/")
	websocket_data = {
		"type": data_type,
		"data": {
			"tool": tool,
			"message": message,
			"timestamp": str(pendulum.now('Asia/Kolkata')),
		}
	}
	ws.send(json.dumps(websocket_data))
	sleep(1)
	ws.close()

onsuccess:
	send_data_to_websocket("SUCCESS", None, "Completed Workflow")

rule all:
	input:
		# combined_results = expand(
		# 		"{base_path}/Analysis/{date}/combined_files/{combined_file}",
		# 		base_path=config['base_path'],
		# 		date=config['analysis_time'].split('_')[0],
		# 		combined_file=['combined_metadata.tsv', 'combined_sequences.fasta'],
		# 	),
		# alignment = expand(
		# 		"{base_path}/Analysis/{date}/alignment/{aligned_file}",
		# 		base_path=config['base_path'],
		# 		date=config['analysis_time'].split('_')[0],
		# 		aligned_file=['combined_sequences_aligned.fasta'],
		# 	),
		# nextstrain = expand(
		# 		"{base_path}/Analysis/{date}/nextstrain/{nextstrain_file}",
		# 		base_path=config['base_path'],
		# 		date=config['analysis_time'].split('_')[0],
		# 		nextstrain_file=['nextstrain_metadata.tsv'],
		# 	),
		analysis_results = expand(
				"{base_path}/Analysis/{date}/reports/{analysis_file}",
				base_path=config['base_path'],
				date=config['analysis_time'].split('_')[0],
				analysis_file=['clade_report.tsv', 'lineage_report.csv'],
				# analysis_file=['clade_report', 'lineage_report', 'mutation_count_report', 'specific_voc_report', 'state_wise'],
			),

include: "rules/update/index.smk"
include: "rules/combine_data/index.smk"
include: "rules/alignment/index.smk"
include: "rules/reports/clade_report.smk"
include: "rules/reports/lineage_report.smk"
# include: "rules/clade_and_lineage/index.smk"

# include: "rules/top_mutation/index.smk"
# include: "rules/voc_table/index.smk"
