import os
import numpy
import arrow
import base64
import pandas
import fuzzyset
import pendulum
import itertools
import subprocess
import collections
from tqdm import tqdm
from Bio import SeqIO
from Bio.Seq import Seq
from pandas import ExcelWriter
from zipfile import ZipFile, ZIP_DEFLATED

rule all:
	input:
		results = expand(
				"{base_path}/combined_files/{date}/{combined_file}",
				base_path=config['base_path'],
				date=str(pendulum.now('Asia/Kolkata')).split('T')[0],
				combined_file=['update_log']
			),
		mutation_results = expand(
				"{base_path}/combined_files/{date}/Analysis/{analysis_file}",
				base_path=config['base_path'],
				date=str(pendulum.now('Asia/Kolkata')).split('T')[0],
				analysis_file=['state_wise', 'top_mutation.xlsx']
			),
		# voi_distribution = os.path.join(config['result_path'], 'voi_distribution', 'voi_distribution.xlsx')

include: "rules/update/index.smk"
include: "rules/combine_data/index.smk"
include: "rules/alignment/index.smk"
include: "rules/clade_and_lineage/index.smk"
include: "rules/top_mutation/index.smk"
